apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine 
        command: ["redis-server", "--appendonly", "yes"] 
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        # 1. Mount the volume inside the container
        volumeMounts:
        - name: redis-data-storage
          mountPath: /data
      # 2. Define where the volume lives on your WSL/Windows host
      volumes:
      - name: redis-data-storage
        hostPath:
          path: /mnt/wsl/redis-data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379